#define SUBMESH_TYPE_UNDEFINED 0
#define SUBMESH_TYPE_OUTFIT 1
#define SUBMESH_TYPE_BODY 2
#define SUBMESH_TYPE_HEAD 3
#define SUBMESH_TYPE_HAIR 4
#define SUBMESH_TYPE_EYEBROW 5
#define SUBMESH_TYPE_L_EYE 6
#define SUBMESH_TYPE_R_EYE 7
#define SUBMESH_TYPE_HEADWEAR 8
#define SUBMESH_TYPE_EARRINGS 9

#define SUBMESH_TYPE_BUFFER 0.5
