#ifndef AVATAR_SUBMESH_PROPERTIES_CGINC
#define AVATAR_SUBMESH_PROPERTIES_CGINC

#define OVR_SUBMESH_TYPE_UNDEFINED 0
#define OVR_SUBMESH_TYPE_OUTFIT 1
#define OVR_SUBMESH_TYPE_BODY 2
#define OVR_SUBMESH_TYPE_HEAD 3
#define OVR_SUBMESH_TYPE_HAIR 4
#define OVR_SUBMESH_TYPE_EYEBROW 5
#define OVR_SUBMESH_TYPE_L_EYE 6
#define OVR_SUBMESH_TYPE_R_EYE 7
#define OVR_SUBMESH_TYPE_HEADWEAR 8
#define OVR_SUBMESH_TYPE_EARRINGS 9

#define OVR_SUBMESH_TYPE_BUFFER 0.5

#endif
